services:
  df-notifier:
    container_name: df-notifier
    build:
      context: ..
      dockerfile: docker/dockerfile
    image: ditch-bot
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=mariadb
    volumes:
      - ../logs:/app/logs           # Папка для логов (опционально)
      - ../database:/app/database   # Папка для базы данных (создаст новую бд если в папке пусто)
      - ../config:/app/config       # Файл .env (ОБЯЗАТЕЛЬНО скопируйте .env_template в .env и заполните своими данными)
    restart: unless-stopped
    command: sh -c "sleep 1200 && uv run notifier.py"
    depends_on:
      - df-updater

  df-updater:
    container_name: df-updater
    image: ditch-bot
    environment:
      - TZ=Europe/Moscow            # Тайм зона для логов
      - DB_HOST=mariadb
    volumes:
      - ../logs:/app/logs           # Папка для логов (опционально)
      - ../database:/app/database   # Папка для базы данных (создаст новую бд если в папке пусто)
      - ../config:/app/config       # Файл .env (ОБЯЗАТЕЛЬНО скопируйте .env_template в .env и заполните своими данными)
    restart: unless-stopped
    command: sh -c "sleep 50 && uv run updater.py"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - ../database:/var/lib/mysql
    restart: unless-stopped