services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./main.sh:/app/main.sh
      - ./logs:/app/logs
      - ./database:/app/database
      - ./.env:/app/.env
    restart: unless-stopped