FROM python:3.12-slim

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Рабочая директория
WORKDIR /app

# Копируем файлы
COPY updater.py .
COPY main.py .
COPY requirements.txt .
COPY src/ ./src/

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir -r requirements.txt